conversation: {}

# The Hugging Face model name of the base model.
base_model: meta-llama/Meta-Llama-3-8B-Instruct

#hyperparameters
epochs: 2
lora_rank: 32
learning_rate: 0.0002
batch_size: 4

# Integrate with Weights & Biases to provide observability into the tuning process.
# Create a W&B account and update these fields if you want observability. 
wandb_entity: markat1
wandb_api_key: f479a3021a39c04f6877c08ebdfe2564a9d6e43f
wandb_project: danish-english-fine-tuning-workshop-1